<?php
include_once('stratge/Visa.php');
include_once('stratge/Cash.php');
include_once('stratge/Cash.php');
include_once('stratge/Cash.php');
include_once('stratge/doctor.php');
include_once('stratge/moka.php');
include_once('stratge/moka.php');
include_once('stratge/bus.php');
include_once('stratge/aaa.php');
;
